### ISSUE TITLE
Data durability 문제

### ISSUE THREAD

**Issue by k-s-young** [gogilyun/ggy_project1#2]
입력받고 수정한 Data 저장 방식을 어떻게 하는게 좋을까요?
1)  MySQL과 같은 DB를 사용할까요?
2) 아님 File입출력 함수를 사용할까요?
어느게 좋을지 의견을 남겨주세요!
@YunJiHyun @kobetty2

**Comment by YunJiHyun** [comment]
파일 입출력 합수를 사용하는 편이 좋을 것 같아요. mysql을 사용하려면 팀원 중에 새로 깔아야해서 파일입출력으로 data를 저장해도 괜찮다고 생각합니다.

**Comment by kobetty2** [comment]
파일입출력함수로 하는것이 더 나을거같아요!
